#!/bin/sh
if [  "$1" == "-n" ]; then
        N=$2
        target=$3
        touch ${TMP}/input.txt
        if [[ "$#" < "3" ]]
        then

                target=${TMP}/input.txt
                cat > $target

        fi
	count=($(wc -l $target))
	x=$count
	while [[ $x > 0 ]]
	do
		if [ $x -lt $N ]
		then
			head -n $x "$target"
			x=0
		else
			head -n $x  "$target" | tail -n +$(( $x - $N + 1))
			x=$((x - $N))
		fi
	done
	rm "${TMP}/input.txt"
else
	target=$1
	touch ${TMP}/input.txt
	if [[ "$#" < "1" ]]
	then
		target=${TMP}/input.txt
		cat > $target
	fi
	tac "$target"
	rm "${TMP}/input.txt"	
fi

